### ISSUE TITLE
page reloads when using RenderSection from MVCViewWithLayout

### ISSUE THREAD

**Issue by ramyothman** [JoshClose/Pjax.Mvc#3]
define this section in main layout
@RenderSection("scripts", required: false)

in any view from this layout 
@section scripts {
    //write any java script here
}

the page performs the ajax load then perform a full reload

**Comment by JoshClose** [comment]
Which version of jquery-pjax are you using?

I'll try to take a look at this over the weekend.

**Comment by ramyothman** [comment]
Hey Thanks,

version 1.9.6,

Regards

**Comment by JoshClose** [comment]
If you use Chrome and check the `Preserve log` box, it'll save the log across page requests. When I tried this out, I was getting a 500 error back from the web page. Basically, any section you have in your view will need to be in the pjax portion of the layout.

In your case, you'll want to add the scripts section. jquery-pjax will actually take an script content on the requested page and run it also.

```html
@if( ViewBag.IsPjaxRequest ?? false )
{
	<title>@ViewBag.Title</title>
	@RenderBody()
	@RenderSection( "Scripts", false )
	return;
}
<!DOCTYPE html>
<html>
...
```
