### ISSUE TITLE
Can't get to work with MVC 5

### ISSUE THREAD

**Issue by lordplagus02** [JoshClose/Pjax.Mvc#4]
I installed the nuget package and added all the relevant constructs and inheritance and attributes etc, according to your instructions, but my ViewBag.IsPjaxRequest is false every time. Is there anything else I was meant to install outside of your instructions? Can you post clearer instructions maybe? Thanks

**Comment by JoshClose** [comment]
Do you have jQuery.pjax setup? https://github.com/defunkt/jquery-pjax 

My documentation was assuming the user had already got jquery.pjax setup and working, and needed the backend .NET components working. Maybe I should put a full example that includes the JavaScript side of things too.

**Comment by lordplagus02** [comment]
It would be great, just a demo solution, doc isn't necessary. Thanks so much. Currently I have a JavaScript implementation and nothing on the MVC side in C#.
On 6 Jul 2015 15:35, Josh Close <notifications@github.com> wrote:Do you have jQuery.pjax setup? https://github.com/defunkt/jquery-pjax 

My documentation was assuming the user had already got jquery.pjax setup and working, and needed the backend .NET components working. Maybe I should put a full example that includes the JavaScript side of things too.

**Comment by JoshClose** [comment]
I will try to do that tonight; like 12+ hours from now. I don't have access to a Windows machine until then. :P

**Comment by JoshClose** [comment]
Sorry, I was busy all night and didn't get a chance to make a full example.

Take a look at the pjax documentation here: https://github.com/defunkt/jquery-pjax

Here is a little example. Put this at the bottom of your page.

```js
<script src="pjax.js"></script>
<script>
$(document).pjax("#pjax-container");
$(document).on("submit", "form", function(event) {
    $.pjax.submit(event, "#pjax-container");
});
</script>
```

**Comment by JoshClose** [comment]
I added an example website to source. You can take a look there.
