### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by MohammadReza10** [JoshClose/Pjax.Mvc#6]
i can not use this package

**Comment by JoshClose** [comment]
What do you mean?

**Comment by MohammadReza10** [comment]
i am installed package
and follow your doc step by step
but when click on a links , all pages redirect instead use pjax !!!

**Comment by codeconqueror** [comment]
I had the same confusion at first.  This only gives you the server side piece of it.

You need to implement the client side piece which is the MoOx/pjax referred to in the readme.  Perhaps the readme could make it clearer.

https://github.com/MoOx/pjax

Once I added that, everything worked perfectly in my .NET Core app.

**Comment by JoshClose** [comment]
I'll make that more clear in the readme.
